CREATE DATABASE grocery_store;


USE grocery_store;


CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


INSERT INTO categories VALUES
(1,'Grains & Cereals'),
(2,'Dairy Products'),
(3,'Snacks & Confectioneries'),
(4,'Personal Care'),
(5,'Household');
   
   
   SELECT * FROM customers;
   SELECT * FROM order_details;
   TRUNCATE TABLE order_details;
SELECT * FROM supplier;
SELECT * FROM employees;
SELECT * FROM products;

SELECT * FROM orders;
SELECT * FROM order_details;

SELECT COUNT(*) FROM supplier;
SELECT COUNT(*) FROM categories;
SELECT COUNT(*) FROM employees;
SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM products;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM order_details;


USE grocery_store;
DESCRIBE supplier;

How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

Which customers have placed the highest number of orders?
SELECT c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_name
ORDER BY total_orders DESC;

Total and average purchase value per customer
SELECT 
c.cust_name,
SUM(od.total_price) AS total_spent,
AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name;


Top 5 customers by total purchase amount
SELECT 
c.cust_name,
SUM(od.total_price) AS total_spent
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name
ORDER BY total_spent DESC
LIMIT 5;


Product Performance

1. How many products exist in each category?
SELECT c.cat_name, COUNT(p.prod_id) AS total_products
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

2. Average price of products by category
SELECT c.cat_name, AVG(p.price) AS avg_price
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

3. Products with highest sales (by quantity)
SELECT p.prod_name, SUM(od.quantity) AS total_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_quantity DESC;

4. Total revenue generated by each product
SELECT p.prod_name, SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_revenue DESC;


5. Product sales by category and supplier
SELECT c.cat_name, s.sup_name, SUM(od.total_price) AS total_sales
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY total_sales DESC;


3 sales and Order Trends

1. Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;

2. Average value per order
SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS sub;


3. Dates with highest number of orders
SELECT order_date, COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

4. Monthly trends in orders and revenue
SELECT 
MONTH(order_date) AS month,
COUNT(o.ord_id) AS total_orders,
SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY MONTH(order_date)
ORDER BY month;

5. Weekday vs Weekend orders
SELECT 
CASE 
    WHEN DAYOFWEEK(order_date) IN (1,7) THEN 'Weekend'
    ELSE 'Weekday'
END AS day_type,
COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;


Supplier Contribution

1. How many suppliers are there?
SELECT COUNT(*) AS total_suppliers
FROM supplier;


2. Which supplier provides the most products?
SELECT s.sup_name, COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY total_products DESC;


3. Average price of products by supplier
SELECT s.sup_name, AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;


4. Suppliers contributing most to revenue
SELECT s.sup_name, SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;


 5 Employee Performance
 
1. How many employees processed orders?
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

2. Employees who handled most orders
SELECT e.emp_name, COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY total_orders DESC;

3. Total sales handled by each employee
SELECT e.emp_name, SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY total_sales DESC;


4. Average order value per employee
SELECT e.emp_name, AVG(order_total) AS avg_order_value
FROM employees e
JOIN (
    SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) AS sub
ON e.emp_id = sub.emp_id
GROUP BY e.emp_name;


6 Order Details Deep Dive

1. Relationship between quantity and total price
SELECT quantity, total_price
FROM order_details
LIMIT 20;

2. Average quantity ordered per product
SELECT p.prod_name, AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;

3. Unit price variation across products
SELECT p.prod_name, od.each_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
ORDER BY p.prod_name;
